# Deep Dive in Pytorch
- 파이토치 사용법을 좀 더 고급화 하기 위해, 책 한 권 [딥러닝 파이토치 교과서]을 정해, 정리해보려고 한다.

## 1. Tensor
- Pytorch는 텐서에 대한 제어를 확실히 해야함.
- 개인적으로, Pytorch와 Tensorflow를 병행해서 사용하다보니, 때때로 많이 헷갈리는 경우가 생김.

### 텐서 생성 및 변환

In [1]:
# Tensor 생성
import torch
print(torch.tensor([[1, 2], [3, 4]]))
print(torch.tensor([[1, 2], [3, 4]], device="cuda:0"))
print(torch.tensor([[1, 2], [3, 4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [3]:
# Tensor -> numpy array
tensor_a = torch.tensor([[1, 2], [3, 4]])
print(tensor_a.numpy())

tensor_gpu = torch.tensor([[1, 2], [3, 4]], device="cuda:0")
print(tensor_gpu.to("cpu").numpy())

# GPU 메모리에 올라가 있는 Tensor는 바로 numpy() 변환 되지 않음
# print(tensor_gpu.numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


### 텐서의 자료형 및 인덱스 조작
**Tensor 자료형**
1. torch.FloatTensor : 32비트 부동 소수점 텐서
2. torch.DoubleTensor : 64비트 부동 소수점 텐서
3. torch.LongTensor : 64비트 부호가 있는 정수

In [5]:
float_tensor = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7])
print(float_tensor[0], float_tensor[1], float_tensor[2])
print(float_tensor[0:3], float_tensor[3:5], float_tensor[-4:-1])

tensor(1.) tensor(2.) tensor(3.)
tensor([1., 2., 3.]) tensor([4., 5.]) tensor([4., 5., 6.])


###  텐서 연산
- 텐서간 연산은 텐서의 타입이 다르면 연산이 불가능
- FloatTensor와 DoubleTensor 간에 사칙 연산을 하면 에러 발생
    - pytorch 1.11 에서는 연산 가능

In [7]:
tensor_a = torch.Tensor([1, 2, 3])
print(tensor_a)
tensor_b = torch.tensor([4, 5, 6])
print(tensor_b)

print(tensor_a + tensor_b)

tensor([1., 2., 3.])
tensor([4, 5, 6])
tensor([5., 7., 9.])


In [8]:
sample_float = torch.FloatTensor([2, 4, 6])
sample_double = torch.DoubleTensor([1, 2, 3])

print(sample_float + sample_double)

tensor([3., 6., 9.], dtype=torch.float64)


In [9]:
sample_float

tensor([2., 4., 6.])

In [10]:
sample_double

tensor([1., 2., 3.], dtype=torch.float64)

### 텐서 차원 조작
- 텐서 차원 조작 방법 : ```view```
    - numpy의 ```reshape```과 유사
- 텐서 결합 : ```stack```, ```cat```
    - ```cat``` : 다른 길이의 텐서를 하나로 병합할 때 사용
- 텐서 차원 교환 : ```t```, ```transpose```
    - ```transpose``` : 행렬 전치 외에도, 차원의 순서 변경 때도 사용
